# Default values for todo-app
environment: dev

# Image registry configuration
imageRegistry: ''

# Backend configuration
backend:
  replicaCount: 2
  image:
    repository: todo-backend
    tag: latest
    pullPolicy: Always # Changed from IfNotPresent to Always
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      memory: '256Mi'
      cpu: '250m'
    limits:
      memory: '512Mi'
      cpu: '500m'

# Frontend configuration
frontend:
  replicaCount: 2
  image:
    repository: todo-frontend
    tag: latest
    pullPolicy: Always # Changed from IfNotPresent to Always
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: '128Mi'
      cpu: '100m'
    limits:
      memory: '256Mi'
      cpu: '500m'

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: '16-alpine'
  auth:
    username: postgres
    password: postgres
    database: todos
  persistence:
    enabled: true
    size: 5Gi
    subPath: pgdata
  resources:
    requests:
      memory: '256Mi'
      cpu: '250m'
    limits:
      memory: '512Mi'
      cpu: '500m'

# Azure Database for PostgreSQL (managed service)
azurePostgres:
  enabled: true
  host: 'psql-k8s-todo-dev.postgres.database.azure.com'
  port: '5432'
  database: 'todos'
  username: 'psqladmin'
  password: 'SuperSecret123!'

# Ingress configuration
ingress:
  enabled: true
