# Default values for todo-app
environment: dev

# Image registry configuration
imageRegistry: ''

# Backend configuration
backend:
  image:
    repository: todo-backend
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000

# Frontend configuration
frontend:
  image:
    repository: todo-frontend
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: '15'
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    size: 1Gi

# Ingress configuration
ingress:
  enabled: false
  className: nginx
  annotations:
    {}
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: todo-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    []
    # - secretName: todo-app-tls
    #   hosts:
    #     - todo-app.example.com
