# Default values for todo-app
environment: dev

# Image registry configuration
imageRegistry: '' # Empty for local, acrk8stododev.azurecr.io for Azure

# Backend configuration
backend:
  replicaCount: 1
  image:
    repository: todo-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      memory: '256Mi'
      cpu: '250m'
    limits:
      memory: '512Mi'
      cpu: '500m'

# Frontend configuration
frontend:
  replicaCount: 1
  image:
    repository: todo-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: '128Mi'
      cpu: '100m'
    limits:
      memory: '256Mi'
      cpu: '500m'

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: '16-alpine'
  persistence:
    enabled: true
    size: 5Gi
    subPath: pgdata
  resources:
    requests:
      memory: '256Mi'
      cpu: '250m'
    limits:
      memory: '512Mi'
      cpu: '500m'

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  host: todo.local
  tls:
    enabled: false
