# Frontend Service - Load balancer for frontend Pods
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todo-app
  labels:
    app: frontend
    tier: web
spec:
  type: ClusterIP

  selector:
    app: frontend
    tier: web

  ports:
    - name: http
      port: 80 # Service listens on port 80
      targetPort: 3000 # Forward to container port 3000
      protocol: TCP
