apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email for renewal notifications (change this!)
    email: dennis.byberg@hotmail.com

    # Secret to store account key
    privateKeySecretRef:
      name: letsencrypt-prod

    # HTTP-01 challenge (proves you own the domain)
    solvers:
      - http01:
          ingress:
            class: nginx
