apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: todo-app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/DennisByberg/k8s-todo
    targetRevision: main
    path: infrastructure/helm/todo-app
    helm:
      values: |
        imageRegistry: "acrk8stododev.azurecr.io"
        backend:
          image:
            pullPolicy: Always
        frontend:
          image:
            pullPolicy: Always
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
