# PVC - Request for persistent storage
# This survives Pod restarts (database data must persist!)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: todo-app
  labels:
    app: postgres
spec:
  accessModes:
    # ReadWriteOnce - Can be mounted read-write by single node
    # (PostgreSQL can only run on one node at a time)
    - ReadWriteOnce
  resources:
    requests:
      # Request 5GB of storage
      storage: 5Gi
  # storageClassName: default (uses cluster default, often Azure Disk in AKS)
