{{- if .Values.azurePostgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-azure-postgres
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.azurePostgres.username }}:{{ .Values.azurePostgres.password }}@{{ .Values.azurePostgres.host }}:{{ .Values.azurePostgres.port }}/{{ .Values.azurePostgres.database }}?sslmode=require"
  POSTGRES_HOST: {{ .Values.azurePostgres.host | quote }}
  POSTGRES_PORT: {{ .Values.azurePostgres.port | quote }}
  POSTGRES_DB: {{ .Values.azurePostgres.database | quote }}
  POSTGRES_USER: {{ .Values.azurePostgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.azurePostgres.password | quote }}
{{- end }}