apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      {{- if not .Values.azurePostgres.enabled }}
      # Wait for postgres to be ready before starting backend (only for in-cluster postgres)
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres service to be ready..."
              until nc -z {{ .Release.Name }}-postgres 5432; do
                echo "Postgres not ready yet, waiting..."
                sleep 2
              done
              echo "Postgres is ready!"
      {{- end }}
      containers:
        - name: backend
          {{- if .Values.imageRegistry }}
          image: "{{ .Values.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          {{- else }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- if .Values.azurePostgres.enabled }}
            # Use Azure Database for PostgreSQL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-azure-postgres
                  key: DATABASE_URL
            {{- else }}
            # Use in-cluster PostgreSQL
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.auth.database }}"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}