apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
  labels:
    app: {{ include "todo-app.name" . }}
data:
  # Database connection string for backend
  DATABASE_URL: "postgresql://todo_user:todo_password@{{ include "todo-app.fullname" . }}-postgres:5432/todo_db"
  
  # Backend API URL for frontend (internal service name)
  NEXT_PUBLIC_API_URL: "http://{{ include "todo-app.fullname" . }}-backend:8000"